hub:
  image: selenium/hub:3.5.3-boron
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.5.3-boron
  links:
    - hub
chrome:
  image: selenium/node-chrome:3.5.3-boron
  links:
    - hub
