hub:
  image: selenium/hub:3.4.0-dysprosium
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.4.0-dysprosium
  links:
    - hub
chrome:
  image: selenium/node-chrome:3.4.0-dysprosium
  links:
    - hub
